{
    "name": "Tieroo – Loyalty cards",
    "summary": "Loyalty cards in Apple Wallet and Google Wallet from Odoo Loyalty. Uses the Tieroo service (free up to 100 cards).",
    "version": "20.0.1.1.9",
    "category": "Sales/Point of Sale",
    "license": "LGPL-3",
    "author": "Tieroo",
    "website": "https://tieroo.com",
    "support": "support@tieroo.com",
    "images": ["static/description/banner.gif"],
    "depends": ["point_of_sale", "loyalty", "mail"],
    "external_dependencies": {"python": ["requests"]},
    "data": [
        "security/ir.access.csv",
        "data/ir_cron.xml",
        "data/mail_template.xml",
        "data/join.xml",
        "views/views.xml",
        "views/join.xml",
        "views/templates.xml",
        "views/join_templates.xml",
    ],
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "application": True,
}
